### ISSUE TITLE
Peer Review/Testing for the revised 

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guide-microprofile-config-profile#23]
### Peer Review conducted on 3 platforms: 
- [x] Mac (Saumya)
- [x] Linux (Saumya)
- [x] Windows (Ruilin)

### Test coverage
- read through the guide
  - the text should be clear
  - no typo
  - ideally, no wrapped lines on the right code pane  
  - check all links
  - check all hotspots
- run end to end
  - copy the commands
  - paste and run the commands

**Comment by saumyapandyaa** [comment]
mac- 
`start>system>pom.xml` is slightly different than `finish>systm>pom.xml` which causes `./scripts/testApp.sh` to fail. This [link](https://www.diffchecker.com/7cNZHdql/) specifies the differences.

**Comment by Ruilin-Ma** [comment]
Windows-
 
Conducted end-to-end test with the [patch branch](https://github.com/OpenLiberty/draft-guide-microprofile-config-profile/pull/24) on Windows machine and found no issues.

**Comment by saumyapandyaa** [comment]
Conducted end-to-end test with the [patch branch](https://github.com/OpenLiberty/draft-guide-microprofile-config-profile/pull/24) on mac and linux with no issues.
