### ISSUE TITLE
SVT Review comments

### ISSUE THREAD

**Issue by danielguinan1** [OpenLiberty/guide-microprofile-config-profile#25]
Great guide that was easy to follow as a developer with basic MicroProfile Config knowledge.  

One comment I have the use of the term "Continuous Deployment" in the following line:
```
Continuous Deployment (CD) offers a solution by enabling the rapid and safe release of software changes.
```
To me, the DevOps concept of CI/CD stands for Continuous Integration/Continuous Delivery.  Even as someone familiar with DevOps processes the terminology can get complicated, and I had to look up both definitions to see how they compare.  It may be helpful to the reader if you add a sentence or two explaining how "Continuous Deployment" compares to the more commonly known "Continuous Delivery" concept so they don't have to do external research.

Other than that everything looks good, and I am interested to see how we can implement config profiles into our SVT applications.

**Comment by mtamboli** [comment]
@gkwan-ibm I also tried this guide. Here is some feedback: I understood from the guide that externalizing microprofile-config and passing to my microservices will provide me flexibility to connect to different instances of system from query. But it was not totally clear how it will help with overall DevOps flow? How will you progress from dev->test->Prod

1. I think it would be good to see how this mpConfig fits in the DevOps pipeline. A diagram with dev and ops may help.
2. To understand how the different profiles (dev, test and prod) will work for system and query communications , I had to dig the scripts in the repository to see how you would you pass the ` -P prod` option to pick a specific config profile.
```
more deployApp.sh 
#!/bin/bash

if [ "$#" -ne 2 ]; then
    echo "Usage: ./deployApp.sh [username] [password]"
    exit 1
fi

USERNAME="$1"
PASSWORD="$2"

mvn -pl system -ntp clean package liberty:create liberty:install-feature liberty:deploy
mvn -pl query -ntp clean package liberty:create liberty:install-feature liberty:deploy

mvn -pl system -ntp \
    -P prod \
    -Dliberty.var.default.username="$USERNAME" \
    -Dliberty.var.default.password="$PASSWORD" \
    liberty:start
mvn -pl query -ntp \
    -Dliberty.var.mp.config.profile="prod" \
    -Dliberty.var.system.user="$USERNAME" \
    -Dliberty.var.system.password="$PASSWORD" \
    liberty:start
-----
mtamboli@monicas-mbp scripts % more testApp.sh  
#!/bin/bash

mvn -pl system -ntp clean package liberty:create liberty:install-feature liberty:deploy
mvn -pl query -ntp clean package liberty:create liberty:install-feature liberty:deploy

mvn -pl system -ntp -P test liberty:start
mvn -pl query -ntp -Dliberty.var.mp.config.profile="test" liberty:start

mvn -pl system -ntp -P test failsafe:integration-test
mvn -pl query -ntp failsafe:integration-test

mvn -pl query -ntp liberty:stop
mvn -pl system -ntp liberty:stop

```

**Comment by gkwan-ibm** [comment]
- [x] remove CD in the title and description
- [x] update the diagrams to have DevOps lifecycle
   - [x] Gilbert will update the diagrams
   - [x] Morgen will add a diagram in the test section
- [x] revisit the test section to hotspot
   - `-P test`
   - `-Dliberty.var.mp.config.profile="test"`
- [x] update the prod section
   - use yaml instead of deploy script
   - users no need to run the yaml. The content just explain
     - liberty.var.mp.config.profile="prod" 
   - make sure the yaml work
     - create Dockerfile for building system and inventory images
     - create yaml file that will be shown in the content
     - above can run in kube with OL operator

**Comment by danielguinan1** [comment]
The updates look good to me.
