### ISSUE TITLE
Laura's review

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/guide-microprofile-config-profile#33]
In general, nice guide. Some style comments but I've also questioned the use of "at ConfigSource level" and "ConfigSource" as it's inconsistent with the docs but also because it doesn't quite make sense here anyway (it's a bit opaque what it's referring to).

** Style comments**
* Nice intro, I like it. :)
* "Creating configuration profile for dev environment" heading should be "Creating a configuration profile for the dev environment" (and similarly for the other headings)
* For simplicity, I think "Each microservice resides in its own" should be "Each microservice is in its own"
* I think "ConfigSources" should be "configuration sources" and link to `https://openliberty.io/docs/latest/external-configuration.html#default` in the docs for more info, rather than to the guide. We need people to get the idea that more info (and more complete info) is available in the docs. The guides don't necessarily include everything; they should only include what's relevant to that guide. And also I think that guide should be updated to use the term "configuration sources" consistently with the docs rather than the jargon-y "ConfigSources".
* Hmm, also, that docs topic says there are *six* default config sources but the linked guide says there are *five*. One needs fixing - can you raise an issue on whichever needs updating, pls? /cc @dmuelle @yeekangc 
*  "For `query` service," should be "For the `query` service,"
* Should it be "DevOps" or "CI/CD" for the name of the lifecycle? @yeekangc ? I feel like DevOps is a broader term whereas this is maybe more specifically about the CI/CD lifecycle, but I could be convinced otherwise---I just want to double-check.
* "Remove the `%dev.*` properties" Should that have an `%` in it? Or should it say "Remove the `dev.*` properties"?
* "Any system.* properties specified in the former thus take precedence over the values in the latter." - I think just spell this out fully: "Any system.* properties specified in `microprofile-config-dev.properties` take precedence over `system.*` property values in `microprofile-config.properties`." - don't make them do the work of parsing the previous sentence when you can just say it in almost as many words anyway. I may have mis-interpreted exactly so check the wording I've used---which actually underlines the point I'm making that repetition is fine in technical writing as long as it helps clarity.
* "Proper testing configuration" -> "A good testing configuration"?
* "aligns the environment closer to" -> "aligns the environment closely with"

**ConfigSource level phrasing**
/cc @dmuelle for input please as the docs and the guides are inconsistent here too.
* The phrase "at ConfigSource level" - I'm not sure this makes sense as a phrase; doesn't it just mean creating profiles in an alternative configuration source, maybe at a higher level than in the property files of each microservice? Instead of talking about "using ConfigSources", can it say something like "higher-level configuration sources" (or something better than that!)?
* I think also there needs to be an intro in the "Creating configuration profile for dev environment" section of the two sub-sections, which describe alternative approaches. I know each sub-section does explain why you might do it but I found it hard to get a mental picture of what was going as I was reading; I think there needs to be something up front to set the scene, then you can reiterate in the sub-sections themselves. For example, "Creating configuration profiles at the property level is useful when only a few configuration properties need to be set differently for each DevOps stage, such as when you require different database connection settings in different environments. It can be particularly useful, however, to create configuration profiles in higher-level configuration sources when you need to manage a large number of configuration properties for different environments." ("higher-level" might not be the right term here but we need to explain why you'd do this, why you'd care to read the "Configuring sources at ConfigSource level" even).

**Comment by shin19991207** [comment]
Hi @lauracowen 

Thank you for the comments.

> "Remove the %dev.* properties" Should that have an % in it? Or should it say "Remove the dev.* properties"?

The `%` should actually be included here because the syntax for configuring properties at the property level looks like this: `%<config_profile_id>.<property_name>=<value>`. FYI, this is also explained in the "Configuring properties at property level" section.

> Hmm, also, that docs topic says there are *six* default config sources but the linked guide says there are *five*. One needs fixing - can you raise an issue on whichever needs updating, pls?

I think it's [the guide](https://openliberty.io/guides/microprofile-config-intro.html#background-concepts) that requires an update because it is missing the `defaultValue` configuration source. I've opened [this issue](https://github.com/OpenLiberty/iguide-microprofile-config-intro/issues/282) to address the problems.

**Comment by yeekangc** [comment]
+1 for "CI/CD".

**Comment by gkwan-ibm** [comment]
close
- comments were addressed
