### ISSUE TITLE
SME review comments

### ISSUE THREAD

**Issue by Emily-Jiang** [OpenLiberty/guide-microprofile-config-profile#7]
Here are some comments:
1. Learn how to use MicroProfile Config Profile => Learn how to use the config profile feature in MicroProfile Config
2. Update all of the "MicroProfile Config Profile" to "the config profile feature in MicroProfile Config" appropriately.
3. After the following paragraph:

> With setting mp.config.profile to development, each %development.* property overrides the value of its original property. For example, the %development.system.httpPort property overrides the system.httpPort property and the value is resolved to 9081.

please add
The property `mp.config.profile` can be set in any of the config sources as well. However, it would be only read at the application starting. Any changes after that will be ignored until the next application start.

**Comment by shin19991207** [comment]
Addressed in https://github.com/OpenLiberty/draft-guide-microprofile-config-profile/pull/8
