### ISSUE TITLE
Update ‘Externalizing environment-specific configurations for CI/CD’ Guided project

### ISSUE THREAD

**Issue by binumesh** [OpenLiberty/guide-microprofile-config-profile#82]
Gilbert, 

As discussed in slack about the editorial changes to the guided project (https://author.skills.network/admin/reviews/4907). For example - 

============================
From -
In the this section, you’ll learn how to use Kubernetes secrets to provide the credentials and how to pass them to the ***query*** service by using MicroProfile Config.
To -
In the next section, you’ll learn how to use Kubernetes secrets to provide the credentials and how to pass them to the ***query*** service by using MicroProfile Config.

and added few missing identifying nouns ***microprofile-config.properties*** to ***microprofile-config.properties*** file

overall, very few minor edits.
==============================

Please re-publish the guided project in the Open Liberty project to include the editorial changes. The latest edited file is available in SN - https://author.skills.network/admin/reviews/4907

**Comment by gkwan-ibm** [comment]
close
- issue was fixed
